# Generated by Django 4.1 on 2022-10-30 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longurl', models.URLField()),
                ('short_url', models.URLField(default='')),
                ('hits_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HitsMetaDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('url_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myurl.urlmodel')),
            ],
        ),
    ]
